name: Validate Build on PR to HF

on:
  pull_request:
    branches:
      - HF
    paths:
      - '**/*.java'     # ⬅️ Trigger only when Java files are changed

jobs:
  build:
    if: github.event.pull_request.changed_files > 0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests
